# Generated by Django 3.1.7 on 2021-07-15 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marksApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='date',
        ),
        migrations.CreateModel(
            name='marksRecord',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('totalMarks', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marksApp.studentinfo')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marksApp.subject')),
            ],
        ),
        migrations.AlterField(
            model_name='marks',
            name='totalMarks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marksApp.marksrecord'),
        ),
    ]
