# Generated by Django 3.1.7 on 2021-07-18 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marksApp', '0002_auto_20210715_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marksrecord',
            name='Student',
        ),
    ]
